### ISSUE TITLE
extra[style]: add favicon

### ISSUE THREAD

**Issue by AdrianSkar** [ana-vela/javascript30-collab#26]
We don't have one yet, 😮

**Comment by AdrianSkar** [comment]
I've tried a couple with [favicon.io](https://favicon.io/favicon-generator/), would any suffice for now or shall we wait until we decide on a color scheme? 
![android-chrome-192x192](https://github.com/ana-vela/javascript30-collab/assets/12052430/8fee3379-a5d1-4f91-8113-1678b36482d0)
![android-chrome-192x192](https://github.com/ana-vela/javascript30-collab/assets/12052430/e35ebf98-510f-4e50-92cd-927222b8a808)

[favicon_io.zip](https://github.com/ana-vela/javascript30-collab/files/12328076/favicon_io.zip)
[favicon_io2.zip](https://github.com/ana-vela/javascript30-collab/files/12328077/favicon_io2.zip)

**Comment by AdrianSkar** [comment]
Following last meeting we'll implement the 1st one and change latter if needed.
- [ ] Include on `index.html`

- [ ] Include on all challenge pages

**Comment by AdrianSkar** [comment]
Working on index.html but not on challenges yet:
![image](https://github.com/ana-vela/javascript30-collab/assets/12052430/aa66f16a-a860-403c-8dc2-9d552c8e82e1)
I'll wait a bit to see if it needs to propagate/catch-up

**Comment by AdrianSkar** [comment]
> Working on index.html but not on challenges yet: ![image](https://user-images.githubusercontent.com/12052430/261070406-aa66f16a-a860-403c-8dc2-9d552c8e82e1.png) I'll wait a bit to see if it needs to propagate/catch-up

Working properly on challenges too.

**Comment by ana-vela** [comment]
The favicon is working well on the landing page and exercise pages. Closing issue.
