### ISSUE TITLE
duplicate folders for 30th exercise

### ISSUE THREAD

**Issue by AdrianSkar** [ana-vela/javascript30-collab#8]
Hi there @ana-vela!  Unless I've got some error I think the 30th exercise has two folders on your exercises one:
![image](https://github.com/ana-vela/javascript30-collab/assets/12052430/6499d1fa-b209-43bb-90f3-6219f3453b52)

**Comment by ana-vela** [comment]
Thanks for letting me know. I removed the duplicate folder.
